"""resolve ambiguous relationships on notifications tables

Revision ID: 008848b435c9
Revises: 9468bf7f3a8a
Create Date: 2025-11-17 16:03:42.450232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '008848b435c9'
down_revision: Union[str, None] = '9468bf7f3a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
