"""change lesson content field to json to support dynamic content

Revision ID: 3280fb1ba4da
Revises: baec17663f93
Create Date: 2025-11-26 13:20:20.117104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3280fb1ba4da'
down_revision: Union[str, None] = 'baec17663f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE lessons
        SET content = jsonb_build_object('text', content)
        WHERE content IS NOT NULL AND content NOT LIKE '{%' AND content NOT LIKE '[%'
        """
    )
    
    op.alter_column('lessons', 'content',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using="content::json")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons', 'content',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
