"""add audio_duration and transcript to messages

Revision ID: 43feca9c4b2f
Revises: cea7680271a3
Create Date: 2025-12-14 01:00:31.625985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43feca9c4b2f'
down_revision: Union[str, None] = 'cea7680271a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('audio_duration', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('transcript', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'transcript')
    op.drop_column('messages', 'audio_duration')
    # ### end Alembic commands ###
