"""add notification_settings to patients

Revision ID: 83053a6d8466
Revises: 800d1d074e7e
Create Date: 2025-12-13 20:01:43.575558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83053a6d8466'
down_revision: Union[str, None] = '800d1d074e7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('notification_settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{"appointments": true, "messages": true, "reminders": true, "updates": false}', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'notification_settings')
    # ### end Alembic commands ###
