"""update transcripts field

Revision ID: 8f11afe12d4e
Revises: 43feca9c4b2f
Create Date: 2025-12-14 17:26:15.493845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f11afe12d4e'
down_revision: Union[str, None] = '43feca9c4b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('original_language', sa.Enum('ENGLISH', 'HAUSA', 'IGBO', 'YORUBA', name='preferredlanguage'), nullable=True))
    op.add_column('messages', sa.Column('transcripts', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('messages', 'transcript')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'transcripts')
    op.drop_column('messages', 'original_language')
    # ### end Alembic commands ###
