"""update nofification tables to match system design

Revision ID: 9468bf7f3a8a
Revises: 1aa56763597c
Create Date: 2025-11-17 15:28:27.391856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9468bf7f3a8a'
down_revision: Union[str, None] = '1aa56763597c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unread_notifications', sa.ARRAY(sa.UUID()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('notifications', sa.Column('course_id', sa.UUID(), nullable=True))
    op.add_column('notifications', sa.Column('track_id', sa.UUID(), nullable=True))
    op.add_column('notifications', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('notifications', sa.Column('created_by', sa.UUID(), nullable=True))
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('check_notification_single_scope', 'notifications', ['course_id', 'track_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_course_id'), 'notifications', ['course_id'], unique=False)
    op.create_index(op.f('ix_notifications_track_id'), 'notifications', ['track_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'tracks', ['track_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'users', ['created_by'], ['id'])
    op.drop_column('notifications', 'read')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_track_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_course_id'), table_name='notifications')
    op.drop_index('check_notification_single_scope', table_name='notifications')
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('notifications', 'created_by')
    op.drop_column('notifications', 'title')
    op.drop_column('notifications', 'track_id')
    op.drop_column('notifications', 'course_id')
    op.drop_table('user_notifications')
    # ### end Alembic commands ###
