"""Add hospital_code and language enums

Revision ID: b484a3d65d89
Revises: 365fc03a8685
Create Date: 2025-12-13 01:55:11.569988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b484a3d65d89'
down_revision: Union[str, None] = '365fc03a8685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Use existing preferredlanguage enum type (already created for Patient model)
    preferredlanguage_enum = postgresql.ENUM('ENGLISH', 'HAUSA', 'IGBO', 'YORUBA', name='preferredlanguage', create_type=False)
    
    op.create_table('triage_chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('triage_case_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('language', preferredlanguage_enum, nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triage_case_id'], ['triage_cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_triage_chat_patient', 'triage_chats', ['patient_id'], unique=False)
    
    # Add hospital_code as nullable first, then populate existing rows
    op.add_column('hospitals', sa.Column('hospital_code', sa.String(length=20), nullable=True))
    
    # Generate codes for existing hospitals: HOSP-XXX-{id first 4 chars}
    op.execute("""
        UPDATE hospitals SET hospital_code = 'HOSP-' || 
            UPPER(SUBSTRING(REGEXP_REPLACE(name, '[^a-zA-Z]', '', 'g'), 1, 4)) || 
            '-' || SUBSTRING(id::text, 1, 3)
        WHERE hospital_code IS NULL
    """)
    
    # Now set NOT NULL constraint
    op.alter_column('hospitals', 'hospital_code', nullable=False)
    op.create_index(op.f('ix_hospitals_hospital_code'), 'hospitals', ['hospital_code'], unique=True)
    
    # First normalize existing language values to uppercase to match enum values
    op.execute("UPDATE triage_cases SET language = UPPER(language) WHERE language IS NOT NULL")
    
    # Convert triage_cases.language from varchar to enum using existing type
    op.execute("ALTER TABLE triage_cases ALTER COLUMN language TYPE preferredlanguage USING language::preferredlanguage")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('triage_cases', 'language',
               existing_type=sa.Enum('ENGLISH', 'HAUSA', 'IGBO', 'YORUBA', name='preferredlanguage'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_hospitals_hospital_code'), table_name='hospitals')
    op.drop_column('hospitals', 'hospital_code')
    op.drop_index('idx_triage_chat_patient', table_name='triage_chats')
    op.drop_table('triage_chats')
    # ### end Alembic commands ###
