"""add conversations and messages

Revision ID: cea7680271a3
Revises: 83053a6d8466
Create Date: 2025-12-13 20:41:57.317164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea7680271a3'
down_revision: Union[str, None] = '83053a6d8466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('idx_conversations_participant_1', 'conversations', ['participant_1_id'], unique=False)
    op.create_index('idx_conversations_participant_2', 'conversations', ['participant_2_id'], unique=False)
    op.create_index('idx_conversations_updated', 'conversations', ['updated_at'], unique=False)
    op.add_column('messages', sa.Column('attachment_name', sa.String(length=255), nullable=True))
    op.create_index('idx_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('idx_messages_sender', 'messages', ['sender_id'], unique=False)
    op.create_index('idx_messages_unread', 'messages', ['conversation_id', 'is_read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_messages_unread', table_name='messages')
    op.drop_index('idx_messages_sender', table_name='messages')
    op.drop_index('idx_messages_conversation_created', table_name='messages')
    op.drop_column('messages', 'attachment_name')
    op.drop_index('idx_conversations_updated', table_name='conversations')
    op.drop_index('idx_conversations_participant_2', table_name='conversations')
    op.drop_index('idx_conversations_participant_1', table_name='conversations')
    op.drop_column('conversations', 'updated_at')
    # ### end Alembic commands ###
