"""add image url to resource table

Revision ID: dd70a3bdb5bd
Revises: 9e4e077caae9
Create Date: 2025-09-11 16:45:33.596234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd70a3bdb5bd'
down_revision: Union[str, None] = '9e4e077caae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'image_url')
    # ### end Alembic commands ###
